unit_test: unit_test.c
	gcc -g -Wall -Wextra -pedantic -ansi -o unit_test unit_test.c

hash_table: hash_table.c
	gcc -g -Wall -Wextra -pedantic -ansi -o hash_table hash_table.c

exec_hash_table:
	./hash_table
